### ISSUE TITLE
Host annotation isn't working

### ISSUE THREAD

**Issue by kgilpin** [conjurinc/salesdemo#1]
Running as user `demo` (a `security_admin`) on a fresh Conjur:

```
[demo] Adding host demo:host:do6NO79LwVaFMyHAmclUCkm9UePskghz to layer demo/myapp/image_processing
Host added
Loading /home/demo/.conjurrc
Using authn host https://conjur/api/authn
Using authn host https://conjur/api/authn
Authenticating demo
 
error: 403 Forbidden
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
/opt/conjur/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-api-4.12.0/lib/conjur/annotations.rb:84:in `block in update_annotation'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-api-4.12.0/lib/conjur/has_attributes.rb:44:in `invalidate'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-api-4.12.0/lib/conjur/annotations.rb:81:in `update_annotation'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-api-4.12.0/lib/conjur/annotations.rb:44:in `[]='
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-cli-4.19.0/lib/conjur/command/resources.rb:145:in `block (3 levels) in <class:Resources>'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/command_support.rb:126:in `call'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/command_support.rb:126:in `execute'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/app_support.rb:290:in `block in call_command'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/app_support.rb:303:in `call'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/app_support.rb:303:in `call_command'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.2/lib/gli/app_support.rb:81:in `run'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-cli-4.19.0/lib/conjur/cli.rb:64:in `run'
/opt/conjur/embedded/lib/ruby/gems/2.1.0/gems/conjur-cli-4.19.0/bin/conjur:26:in `<top (required)>'
/usr/local/bin/conjur:23:in `load'
/usr/local/bin/conjur:23:in `<main>'error: 403 Forbidden
Loading /home/demo/.conjurrc
Using authn host https://conjur/api/authn
Using authn host https://conjur/api/authn
Authenticating demo
 
error: 403 Forbidden
```

**Comment by dustinmm80** [comment]
i ran this as a member of security_admin, are you as well?

**Comment by kgilpin** [comment]
Fixed in https://github.com/conjurinc/salesdemo/commit/dad835a6106627109d7fa2cbd0ee298d18c97fbd

**Comment by kgilpin** [comment]
The problem was that the account name is hardcoded to salesdemo, which is correct on the trial appliances, but I was using the demo appliance that uses Conjur account name `demo`.
